apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 5m
  upgrade:
    remediation:
      strategy: uninstall
  chart:
    spec:
      chart: cilium
      version: 1.18.2
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
  valuesFrom:
    - kind: ConfigMap
      name: cilium-values
      valuesKey: values.yaml