apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "host-firewall"
spec:
  description: "Set ingress host firewall restrictions and exceptions"
  nodeSelector:
    matchLabels:
      node-access: firewall
  ingress:
  - fromEntities:
  # Allow all traffic from the cluster
    - cluster
  # # Example Allow exceptions to access kube-apiserver
  # - fromCIDR:
  #   - 192.168.1.1/32
  #   toPorts:
  #   - ports:
  #     - port: "6443"
  #       protocol: "TCP"
  # # Example Allow exceptions to access LoadBalancerIP
  # - fromCIDR:
  #   - 192.168.1.1/32
  #   toPorts:
  #   - ports:
  #     - port: "443"
  #       protocol: "TCP"
  #     - port: "80"
  #       protocol: "TCP"
  #     - port: '31196'
  #       protocol: TCP
  #     - port: '32287'
  #       protocol: TCP