apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-device-plugin-gpu
  namespace: intel
spec:
  interval: 5m
  chart:
    spec:
      chart: intel-device-plugins-gpu
      version: 0.32.1
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: intel
  valuesFrom:
    - kind: ConfigMap
      name: idpg-values
      valuesKey: values.yaml