apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring  
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 77.1.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community 
        namespace: monitoring
  valuesFrom:
    - kind: ConfigMap
      name: kube-prom-stack-values
      valuesKey: values.yaml
    - kind: Secret
      name: kube-prom-stack-secrets
      valuesKey: secrets.yaml