apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - helm-repository.yaml
  - helm-release.yaml
configMapGenerator:
  - name: kube-prom-stack-values
    files:
      - values.yaml
secretGenerator:
  - name: kube-prom-stack-secrets
    files:
      - secrets.yaml=secrets.enc.yaml
    options:
      disableNameSuffixHash: true
generatorOptions:
  disableNameSuffixHash: true
configurations:
  - kustomizeconfig.yaml