alertmanager:
  alertmanagerSpec:
    replicas: 1
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
grafana:
  enabled: true
  plugins:
    - victoriametrics-logs-datasource
  ingress:
    enabled: true
    hosts:
      - grafana.sonda.red.local
    path: /
    annotations:
      cert-manager.io/cluster-issuer: sonda-red-local
      kubernetes.io/ingress.class: nginx
    tls:
      - hosts:
          - grafana.sonda.red.local
        secretName: grafana-tls

  ## Configure additional grafana datasources (passed through tpl)
  ## ref: https://grafana.com/docs/grafana/latest/administration/provisioning/#datasources
  additionalDataSources:
    - name: VictoriaLogs
      type: victoriametrics-logs-datasource
      access: proxy
      url: http://victorialogs-victoria-logs-single-server.monitoring:9428
      editable: true
      jsonData:
        tlsSkipVerify: true
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "default"
          orgId: 1
          folder: ""
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default

  dashboards:
    default:
      victorialogs-explorer:
        gnetId: 22759
        datasource: VictoriaLogs
      intel-xpu-manager:
        url: https://raw.githubusercontent.com/intel/xpumanager/refs/heads/master/deployment/kubernetes/monitoring/grafana-dashboard.json
        datasource: Prometheus
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: intel-xpumanager
        metrics_path: /metrics
        scrape_interval: 15s
        scrape_protocols: [OpenMetricsText1.0.0, PrometheusText0.0.4]
        fallback_scrape_protocol: PrometheusText0.0.4
        static_configs:
          - targets: ['intel-xpumanager.intel.svc:29999']
    retention: 1d
    retentionSize: 10GB
    replicas: 1
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
    # Enable cross-namespace ServiceMonitor discovery for XPU metrics
    serviceMonitorNamespaceSelector: {}
    # Enable cross-namespace PodMonitor discovery
    podMonitorNamespaceSelector: {}
    # Enable cross-namespace PrometheusRule discovery
    ruleNamespaceSelector: {}
  ingress:
    enabled: true
    hosts:
      - prometheus.sonda.red.local
    path: /
    annotations:
      cert-manager.io/cluster-issuer: sonda-red-local
      kubernetes.io/ingress.class: nginx
    tls:
      - hosts:
          - prometheus.sonda.red.local
        secretName: prometheus-tls