apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openwebui
  namespace: openwebui
spec:
  interval: 5m
  chart:
    spec:
      chart: open-webui
      version: 8.10.0
      sourceRef:
        kind: HelmRepository
        name: openwebui
        namespace: openwebui
  valuesFrom:
    - kind: ConfigMap
      name: openwebui-values
      valuesKey: values.yaml
    - kind: Secret
      name: openwebui-secrets
      valuesKey: secrets.yaml