architecture: standalone

auth:
  enabled: false
  sentinel: false
usePassword: false

persistence:
  enabled: true
  size: 8Gi

master:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi

replica:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi