apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/rancher/system-upgrade-controller/master/manifests/system-upgrade-controller.yaml
  - upgrade-plan.yml