apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: intel-device-plugins
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/intel/intel-device-plugins-for-kubernetes
  ref:
    tag: v0.32.1
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nfd-node-feature-rules
  namespace: flux-system
spec:
  interval: 10m
  path: ./deployments/nfd/overlays/node-feature-rules
  prune: true
  sourceRef:
    kind: GitRepository
    name: intel-device-plugins
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: intel-gpu-plugin
  namespace: intel
spec:
  interval: 10m
  path: ./deployments/gpu_plugin
  prune: true
  sourceRef:
    kind: GitRepository
    name: intel-device-plugins