apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: system-upgrade-controller
  namespace: system-upgrade
spec:
  interval: 1h
  url: https://github.com/rancher/system-upgrade-controller
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-upgrade-controller
  namespace: system-upgrade
spec:
  interval: 1h
  path: ./manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: system-upgrade-controller
  wait: true
