apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "host-firewall"
spec:
  description: "Set ingress host firewall restrictions and exceptions"
  nodeSelector:
    matchLabels:
      node-access: firewall
  ingress:
  - fromEntities:
  # Allow all traffic from the cluster
    - cluster
  # Allow all traffic from DC
  - fromCIDR:
    - {{ .Values.cilium.hostFirewall.DCNetworkCIDR }}
  # Allow exceptions to access kube-apiserver
  - fromCIDR:
    {{- range .Values.cilium.hostFirewall.KubeAPIServerAccessCIDR }}
    - {{ . }}
    {{- end }}
    toPorts:
    - ports:
      - port: "6443"
        protocol: "TCP"
  # Allow exceptions to access LoadBalancerIP
  - fromCIDR:
    {{- range .Values.cilium.hostFirewall.LoadBalancerIP }}
    - {{ . }}
    {{- end }}
    toPorts:
    - ports:
      - port: "443"
        protocol: "TCP"
      - port: "80"
        protocol: "TCP"
      - port: '31196'
        protocol: TCP
      - port: '32287'
        protocol: TCP