apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
resources:
  - metallb-ns.yaml
  - helm-repository.yaml
  - helm-release.yaml
configMapGenerator:
  - name: metallb-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true