apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: database
spec:
  interval: 5m
  chart:
    spec:
      chart: redis
      version: 21.2.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: database
  valuesFrom:
    - kind: ConfigMap
      name: redis-values
      valuesKey: values.yaml