apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-modelkits
  namespace: vllm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "local-path"
  resources:
    requests:
      storage: 100Gi