apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: dual-gpu-claim
  namespace: vllm
spec:
  spec:
    devices:
      requests:
      - name: gpu
        exactly:
          allocationMode: ExactCount
          count: 2
          selectors:
            - cel:
                expression: 'device.attributes["model"]["string"] == "A770"'
          deviceClassName: gpu.intel.com
---
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: single-gpu-claim
  namespace: vllm
spec:
  spec:
    devices:
      requests:
      - name: gpu
        exactly:
          allocationMode: ExactCount
          count: 1
          selectors:
            - cel:
                expression: 'device.attributes["model"]["string"] == "A770"'
          deviceClassName: gpu.intel.com