apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: dual-gpu-claim
  namespace: vllm
spec:
  spec:
    devices:
      requests:
      - name: gpu
        selectors:
          - cel:
              expression: 'device.capacity["gpu.intel.com"].memory.compareTo(quantity("16Gi")) >= 0'
        exactly:
          allocationMode: ExactCount
          count: 2
          deviceClassName: gpu.intel.com
---
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: single-gpu-claim
  namespace: vllm
spec:
  spec:
    devices:
      requests:
      - name: gpu
        selectors:
          - cel:
              expression: 'device.capacity["gpu.intel.com"].memory.compareTo(quantity("16Gi")) >= 0'
        exactly:
          allocationMode: ExactCount
          count: 1
          deviceClassName: gpu.intel.com