apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc-set-nuc
  namespace: github
spec:
  interval: 5m
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.12.1
      sourceRef:
        kind: HelmRepository
        name: arc
        namespace: github
  valuesFrom:
    - kind: ConfigMap
      name: arc-set-nuc-values
      valuesKey: values.yaml
    - kind: Secret
      name: arc-set-nuc-secrets
      valuesKey: secrets.yaml