## githubConfigUrl is the GitHub url for where you want to configure runners
## ex: https://github.com/myorg/myrepo or https://github.com/myorg
githubConfigUrl: "https://github.com/sonda-red"

## maxRunners is the max number of runners the autoscaling runner set will scale up to.
# maxRunners: 5

## minRunners is the min number of idle runners. The target number of runners created will be
## calculated as a sum of minRunners and the number of jobs assigned to the scale set.
minRunners: 1

# runnerGroup: "default"

## name of the runner scale set to create.  Defaults to the helm release name
# runnerScaleSetName: ""

## A self-signed CA certificate for communication with the GitHub server can be
## provided using a config map key selector. If `runnerMountPath` is set, for
## each runner pod ARC will:
## - create a `github-server-tls-cert` volume containing the certificate
##   specified in `certificateFrom`
## - mount that volume on path `runnerMountPath`/{certificate name}
## - set NODE_EXTRA_CA_CERTS environment variable to that same path
## - set RUNNER_UPDATE_CA_CERTS environment variable to "1" (as of version
##   2.303.0 this will instruct the runner to reload certificates on the host)
##
## If any of the above had already been set by the user in the runner pod
## template, ARC will observe those and not overwrite them.
githubServerTLS:
  certificateFrom:
    configMapKeyRef:
      name: sonda-red-intra-root-ca
      key: ca.crt
  runnerMountPath: /usr/local/share/ca-certificates/

## Configure the runner pods to operate in Kubernetes container mode so that
## workflow jobs can launch ephemeral pods instead of using a DinD sidecar.
containerMode:
  type: kubernetes

## Custom pod template for the runner pods. This replaces the previous DinD
## configuration and mounts the in-cluster trust bundle so that the runners trust
## internal services such as Harbor.
template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command:
          - /home/runner/run.sh
        env:
          - name: ACTIONS_RUNNER_CONTAINER_HOOKS
            value: /home/runner/k8s/index.js
          - name: ACTIONS_RUNNER_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: "true"
          - name: NODE_EXTRA_CA_CERTS
            value: /usr/local/share/ca-certificates/sonda-red-intra-root-ca/ca.crt
          - name: RUNNER_UPDATE_CA_CERTS
            value: "1"
        volumeMounts:
          - name: work
            mountPath: /home/runner/_work
          - name: harbor-registry-ca
            mountPath: /usr/local/share/ca-certificates/sonda-red-intra-root-ca
            readOnly: true
    volumes:
      - name: work
        emptyDir: {}
      - name: harbor-registry-ca
        configMap:
          name: sonda-red-intra-root-ca
          items:
            - key: ca.crt
              path: ca.crt
