apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc
  namespace: github
spec:
  interval: 5m
  chart:
    spec:
      chart: arc
      version: 1.17.1
      sourceRef:
        kind: HelmRepository
        name: arc
        namespace: github
  valuesFrom:
    - kind: ConfigMap
      name: arc-values
      valuesKey: values.yaml
    - kind: Secret
      name: arc-secrets
      valuesKey: secrets.yaml