apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: arc
  namespace: github
spec:
  interval: 1m
  type: oci
  url: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller