apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: github
resources:
  - namespace.yaml
  - helm-repository.yaml
  - helm-release.yaml
configMapGenerator:
  - name: arc-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
configurations:
  - kustomizeconfig.yaml