apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: intel-gpu-claim
  namespace: monitoring
spec:
  spec:
    devices:
      requests:
        - deviceClassName: gpu.intel.com
