alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    retention: 3d
    retentionSize: 8Gi
    replicas: 3
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

grafana:
  enabled: false