apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  sonda.red.intra.server: |
    sonda.red.intra:53 {
        errors
        cache 30
        reload
        template IN A sonda.red.intra {
            match ".*\.sonda\.red\.intra"
            answer "{{ .Name }} 60 IN A 192.168.1.240"
        }
    }