apiVersion: v1
kind: Node
metadata:
  name: sonda-01
  labels:
    sw-backend: "true"
    node-role.kubernetes.io/nuc: "true"
---
apiVersion: v1
kind: Node
metadata:
  name: sonda-02
  labels:
    sw-volume: "true"
    node-role.kubernetes.io/worker: "true"
    node-role.kubernetes.io/nuc: "true"
---
apiVersion: v1
kind: Node
metadata:
  name: sonda-core
  labels:
    sw-backend: "true"
    node-role.kubernetes.io/gpu: "true"
    node-role.kubernetes.io/worker: "true"