apiVersion: v1
kind: Node
metadata:
  name: sonda-01
  labels:
    sw-backend: "true"
---
apiVersion: v1
kind: Node
metadata:
  name: sonda-02
  labels:
    sw-volume: "true"
---
apiVersion: v1
kind: Node
metadata:
  name: sonda-core
  labels:
    sw-backend: "true"