apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 5m
  upgrade:
    remediation:
      strategy: uninstall
  chart:
    spec:
      chart: minio
      version: 17.0.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: minio
  valuesFrom:
    - kind: ConfigMap
      name: minio-values
      valuesKey: values.yaml
    - kind: Secret
      name: minio-secrets
      valuesKey: secrets.yaml