apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio
resources:
  - minio-ns.yaml
  - helm-repository.yaml
  - helm-release.yaml
configMapGenerator:
  - name: minio-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
configurations:
  - kustomizeconfig.yaml