mode: standalone

persistence:
  enabled: true
  size: 600Gi
  storageClass: "local-path"

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "2Gi"
    cpu: "1"

replicas: 1

buckets:
  - name: sonda-data
    policy: none
    purge: false
console:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hostname: minio.sonda.red.local
    labels: {}
      # node-role.kubernetes.io/ingress: platform
    annotations: 
      cert-manager.io/cluster-issuer: sonda-red-local-ca
    path: /
    tls: true

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/gpu
              operator: In
              values:
                - "true"
