apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trust-manager
  namespace: cert-manager
spec:
  interval: 5m
  dependsOn:
    - name: cert-manager
  upgrade:
    remediation:
      strategy: uninstall
  chart:
    spec:
      chart: trust-manager
      version: 0.20.1
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager