apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - namespace.yaml
  - helm-release-cert-manager.yaml  
  - helm-release-trust-manager.yaml
  - issuer-ca.yaml
  - root-ca.yaml
configMapGenerator:
  - name: cert-manager-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true