apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: sonda-red-intra-root-ca
spec:
  sources:
    - secret:
        name: sonda-local-root-ca-key-pair
        key: tls.crt
        namespace: cert-manager
  target:
    configMap:
      key: ca.crt
      name: sonda-red-intra-root-ca
      namespaceSelector:
        matchLabels:
          trust.sonda.red/root-ca: "true"
