apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-device-operator
  namespace: intel
spec:
  interval: 5m
  chart:
    spec:
      chart: intel-device-plugins-operator
      version: 0.32.1
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: intel
  valuesFrom:
    - kind: ConfigMap
      name: ido-values
      valuesKey: values.yaml
    - kind: Secret
      name: ido-secrets
      valuesKey: secrets.yaml