apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: intel
resources:
  - namespace.yaml
  - helm-repository.yaml
  - helm-release.yaml
  - gpu-plugin.yaml
  - gpu-plugin-overlay.yaml
configMapGenerator:
  - name: ido-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
configurations:
  - kustomizeconfig.yaml