sharedDevNum: 1
logLevel: 2
resourceManager: false
enableMonitoring: true
allocationPolicy: "none"

nodeSelector:
  node-role.kubernetes.io/gpu: "true"

nodeFeatureRule: true
devices:
  gpu: true

tolerations:
  - key: "node-role.kubernetes.io/gpu"
    operator: "Exists"
    effect: "NoSchedule"