apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seaweedfs
  namespace: seaweedfs
spec:
  interval: 5m
  chart:
    spec:
      chart: seaweedfs
      version: 4.0.386
      sourceRef:
        kind: HelmRepository
        name: seaweedfs
        namespace: seaweedfs
    upgrade:
      remediation:
        strategy: uninstall
  valuesFrom:
    - kind: ConfigMap
      name: seaweedfs-values
      valuesKey: values.yaml
