apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: seaweedfs
resources:
  - seaweedfs-ns.yaml
  #- helm-repository.yaml
  #- helm-release.yaml
configMapGenerator:
  - name: seaweedfs-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true