apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victorialogs
  namespace: monitoring  
spec:
  interval: 5m
  chart:
    spec:
      chart: victoria-logs-single
      version: 0.11.11
      sourceRef:
        kind: HelmRepository
        name: vm
        namespace: monitoring
  valuesFrom:
    - kind: ConfigMap
      name: vl-values
      valuesKey: values.yaml