apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - helm-repository.yaml
  - helm-release.yaml
configMapGenerator:
  - name: vl-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
configurations:
  - kustomizeconfig.yaml