apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: database
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 18.0.11
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: database
  valuesFrom:
    - kind: ConfigMap
      name: postgresql-values
      valuesKey: values.yaml
    - kind: Secret
      name: postgresql-secrets
      valuesKey: secrets.yaml