apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - helm-release.yaml
configMapGenerator:
  - name: postgresql-values
    files:
      - values.yaml
secretGenerator:
  - name: postgresql-secrets
    files:
      - secrets.yaml=secrets.enc.yaml
    options:
      disableNameSuffixHash: true
generatorOptions:
  disableNameSuffixHash: true
configurations:
  - kustomizeconfig.yaml