apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argo
spec:
  project: default

  source:
    repoURL: 'https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd'
    chart: argocd
    targetRevision: 7.8.27
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: argo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true