apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: harbor
resources:
  - harbor-ns.yaml
  - helm-repository.yaml
  - helm-release.yaml
configMapGenerator:
  - name: harbor-values
    files:
      - values.yaml
secretGenerator:
  - name: harbor-secrets
    files:
      - secrets.yaml=secrets.enc.yaml
    options:
      disableNameSuffixHash: true
generatorOptions:
  disableNameSuffixHash: true
configurations:
  - kustomizeconfig.yaml