apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-xpumanager
spec:
  template:
    spec:
      containers:
      - name: xpumd
        startupProbe:
          httpGet:
            path: /metrics
            port: 29999
          # Make startup probe more forgiving
          initialDelaySeconds: 30        # Wait 30s before first check (default: 0)
          periodSeconds: 10              # Check every 10s (default: 10)
          timeoutSeconds: 5              # 5s timeout per check (default: 1)
          successThreshold: 1            # 1 success needed (default: 1)
          failureThreshold: 6            # Allow 6 failures = 60s total (default: 3)
        readinessProbe:
          httpGet:
            path: /metrics
            port: 29999
          # Also make readiness probe more forgiving
          initialDelaySeconds: 10        # Wait 10s before first check
          periodSeconds: 5               # Check every 5s
          timeoutSeconds: 3              # 3s timeout per check
          successThreshold: 1            # 1 success needed
          failureThreshold: 3            # Allow 3 failures = 15s
        livenessProbe:
          httpGet:
            path: /metrics
            port: 29999
          # Liveness probe - less aggressive
          initialDelaySeconds: 60        # Wait 60s before first check
          periodSeconds: 30              # Check every 30s
          timeoutSeconds: 5              # 5s timeout per check
          successThreshold: 1            # 1 success needed
          failureThreshold: 3            # Allow 3 failures = 90s
