apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-xpumanager
spec:
  template:
    spec:
      # Only run on nodes with Intel GPU hardware
      nodeSelector:
        intel.feature.node.kubernetes.io/gpu: "true"  # Intel GPU present
      # Alternative: specific node selector if needed
      # nodeSelector:
      #   kubernetes.io/hostname: sonda-02
      containers:
      - name: xpumd
        # Use custom XPU Manager image
        image: ghcr.io/soliddowant/xpumanager:1.2.41