apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - xpumanager.yaml
  - service.yaml
#  - service-monitor.yaml
# Ensure all resources are deployed to the intel namespace
namespace: intel