apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - xpumanager.yaml
  - https://raw.githubusercontent.com/intel/xpumanager/v1.3.2/deployment/kubernetes/monitoring/service-intel-xpum.yaml
  - https://raw.githubusercontent.com/intel/xpumanager/v1.3.2/deployment/kubernetes/monitoring/servicemonitor-intel-xpum.yaml

# Ensure all resources are deployed to the intel namespace
namespace: intel

# Use JSON patches for more reliable patching - target any DaemonSet
patches:
- target:
    kind: DaemonSet
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: ghcr.io/soliddowant/xpumanager:1.2.41