apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: intel-xpumanager
  labels:
    app: intel-xpumanager
spec:
  selector:
    matchLabels:
      app: intel-xpumanager
  namespaceSelector:
    matchNames:
      - intel
  endpoints:
    - port: metrics
      path: /metrics
      interval: 5s