apiVersion: v1
kind: Service
metadata:
  labels:
    app: intel-xpumanager
  name: intel-xpumanager
  namespace: intel
spec:
  ports:
  - name: metrics
    port: 29999
    protocol: TCP
  selector:
    app: intel-xpumanager
  sessionAffinity: None
