apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: example
  namespace: example
spec:
  interval: 5m
  chart:
    spec:
      chart: example
      version: 1.17.1
      sourceRef:
        kind: HelmRepository
        name: example
        namespace: example
  valuesFrom:
    - kind: ConfigMap
      name: example-values
      valuesKey: values.yaml
    - kind: Secret
      name: example-secrets
      valuesKey: secrets.yaml