apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/your-org/cluster-management.git
        revision: main
        directories:
          # Include all app manifests in the infra sub directories
          - path: infra/**/*
    - git:
        repoURL: https://github.com/your-org/cluster-management.git
        revision: main
        files:
          # Include all app manifests in the infra sub directories
          - path: infra/**/app.yml
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/your-org/cluster-management.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
            - CreateNamespace=true
            - PruneLast=true
