apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfd
  namespace: nfd
spec:
  interval: 5m
  chart:
    spec:
      chart: nfd
      version: 0.17.3
      sourceRef:
        kind: HelmRepository
        name: nfd
        namespace: nfd
  valuesFrom:
    - kind: ConfigMap
      name: nfd-values
      valuesKey: values.yaml