apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nfd
resources:
  - namespace.yaml
  - helm-repository.yaml
  - helm-release.yaml
  - intel-device-plugins.yaml
configMapGenerator:
  - name: nfd-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
configurations:
  - kustomizeconfig.yaml