apiVersion: v1
kind: ConfigMap
metadata:
  name: buildkit-config
  namespace: buildkit
data:
  buildkitd.toml: |
    # Simple BuildKit daemon configuration
    debug = false
    root = "/var/lib/buildkit"
    
    [grpc]
      address = [ "tcp://0.0.0.0:1234" ]
    
    [worker.oci]
      enabled = true
      platforms = [ "linux/amd64" ]
      snapshotter = "overlayfs"
    
    [worker.containerd]
      enabled = false
    
    [registry."harbor.sonda.red.intra"]
      http = false
      insecure = false