apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildkit
  namespace: buildkit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buildkit
  template:
    metadata:
      labels:
        app: buildkit
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: install-trust-bundle
          image: moby/buildkit:rootless
          command:
            - /bin/sh
            - -c
          args:
            - |
              set -euo pipefail
              cp /etc/ssl/certs/ca-certificates.crt /certs/ca-certificates.crt
              cat /trust/ca.crt >> /certs/ca-certificates.crt
          volumeMounts:
            - name: ca-store
              mountPath: /certs
            - name: trust-bundle
              mountPath: /trust
      containers:
        - name: buildkitd
          image: moby/buildkit:rootless
          env:
            - name: BUILDKITD_FLAGS
              value: --addr tcp://0.0.0.0:1234
            - name: SSL_CERT_FILE
              value: /etc/ssl/certs/ca-certificates.crt
          ports:
            - containerPort: 1234
              name: grpc
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 4Gi
          readinessProbe:
            tcpSocket:
              port: grpc
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: grpc
            initialDelaySeconds: 30
            periodSeconds: 20
          volumeMounts:
            - name: ca-store
              mountPath: /etc/ssl/certs/ca-certificates.crt
              subPath: ca-certificates.crt
              readOnly: true
            - name: trust-bundle
              mountPath: /etc/sonda-red
              readOnly: true
      volumes:
        - name: ca-store
          emptyDir: {}
        - name: trust-bundle
          configMap:
            name: sonda-red-intra-root-ca
