apiVersion: v1
kind: Service
metadata:
  name: buildkit
  namespace: buildkit
spec:
  type: ClusterIP
  selector:
    app: buildkit
  ports:
    - name: grpc
      port: 1234
      targetPort: grpc
      protocol: TCP
    - name: debug
      port: 6060
      targetPort: debug
      protocol: TCP
