apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - helm-repository.yaml
  - helm-release.yaml
configMapGenerator:
  - name: ingress-nginx-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true